if(CONFIG_TESTING_OPTIONS)
    set(CONFIG_WPS_TESTING ON)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_TESTING_OPTIONS")
endif()

set(NEED_RC4 ON)
set(NEED_AES ON)
set(NEED_MD5 ON)
set(NEED_SHA1 ON)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DHOSTAPD")

if(CONFIG_TAXONOMY)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_TAXONOMY")
endif()

if(CONFIG_MODULE_TESTS)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_MODULE_TESTS")
endif()

if(CONFIG_WPA_TRACE)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DWPA_TRACE -funwind-tables")
    set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -rdynamic")
endif()

if(CONFIG_WPA_TRACE_BFD)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DWPA_TRACE_BFD")
endif()

if(CONFIG_ELOOP_POLL)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_ELOOP_POLL")
endif()

if(CONFIG_ELOOP_EPOLL)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_ELOOP_EPOLL")
endif()

if(CONFIG_ELOOP_KQUEUE)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_ELOOP_KQUEUE")
endif()

if(CONFIG_CODE_COVERAGE)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -O0 -fprofile-arcs -ftest-coverage")
endif()

if(CONFIG_NO_RADIUS)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_NO_RADIUS")
    set(CONFIG_NO_ACCOUNTING ON)
endif()

if(CONFIG_NO_ACCOUNTING)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_NO_ACCOUNTING")
endif()

if(CONFIG_NO_VLAN)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_NO_VLAN")
endif()

if(CONFIG_FULL_DYNAMIC_VLAN)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_FULL_DYNAMIC_VLAN")
endif()

if(CONFIG_VLAN_NETLINK)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_VLAN_NETLINK")
endif()

if(CONFIG_HS20)
    set(CONFIG_PROXYARP ON)
endif()

if(CONFIG_PROXYARP)
    set(CONFIG_L2_PACKET ON)
endif()

if(CONFIG_SUITEB)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_SUITEB")
endif()

if(CONFIG_OCV)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_OCV")
endif()

if(CONFIG_IEEE80211R)
    set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DCONFIG_IEEE80211R -DCONFIG_IEEE80211R_AP")
    set(NEED_AES_UNWRAP ON)
    set(NEED_AES_SIV ON)
    set(NEED_ETH_P_OUI ON)
    set(NEED_HMAC_SHA256_KDF ON)
endif()



set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS}  -DNEED_AP_MLME -DCONFIG_ETH_P_OUI -DCONFIG_HS20 -DCONFIG_INTERWORKING \
    -DCONFIG_WPS -DCONFIG_PROXYARP -DCONFIG_IPV6 -DCONFIG_AIRTIME_POLICY \
    -DCONFIG_PTKSA_CACHE -DIEEE8021X_EAPOL -DCONFIG_FST -DCONFIG_MACSEC -DCONFIG_PASN -DCONFIG_SAE -DCONFIG_TDLS")
